# Generated by Django 3.2.8 on 2021-10-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default-image.png', null=True, upload_to='static/images/'),
        ),
    ]
