# Generated by Django 3.2.8 on 2021-10-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20211012_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.product', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.user', verbose_name='name'),
        ),
    ]
