# Generated by Django 3.2.8 on 2021-10-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20211012_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='user',
        ),
    ]
