# Generated by Django 3.2.8 on 2021-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_rename_user_name_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
    ]
