# Generated by Django 3.2.8 on 2021-10-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
